version: "2"
services:
  resourcespace:
    image: rukongai/resourcespace
    restart: unless-stopped
    depends_on:
      - resourcespace-db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./include:/var/www/html/include
      - ./filestore:/var/www/html/filestore
    networks:
      - backend
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.rs.rule: Host(`host.tld.com`)
      traefik.http.routers.rs.entrypoints: web-secure
      traefik.http.routers.rs.middlewares: local-ipwhitelist@file
      traefik.http.services.rs.loadbalancer.server.port: 80
  
  resourcespace-db:
    image: lscr.io/linuxserver/mariadb
    container_name: resourcespace-db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=
      - TZ=America/Denver
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - ./config/db:/config
    restart: unless-stopped
    networks:
      - backend

networks:
  frontend:
    external: true
  backend:
