version: "2"
services:
  resourcespace:
    image: rukongai/resourcespace
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    depends_on:
      - resourcespace-db
    volumes:
      - ./config/www/include:/config/www/resourcespace/include
      - ./config/www/filestore:/config/www/resourcespace/filestore
    networks:
      - backend
    ports:
      - 80:80
      - eden
    labels:
      traefik.enable: true
      traefik.http.routers.space.rule: Host(`print.worldforge.dev`)
      traefik.http.routers.space.entrypoints: web-secure
      traefik.http.routers.space.middlewares: local-ipwhitelist@file
      traefik.http.services.space.loadbalancer.server.port: 80
  
  resourcespace-db:
    image: lscr.io/linuxserver/mariadb
    container_name: resourcespace-db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=rsFabrial902!
      - TZ=America/Denver
      - MYSQL_DATABASE=resourcespace
      - MYSQL_USER=resourcespace
      - MYSQL_PASSWORD=rsFabrial902!
    volumes:
      # - /preservation/appdata/docker/resourcespace/mariadb:/config
      - ./config/db:/config
    restart: unless-stopped
    networks:
      - backend

networks:
  eden:
    external: true
  backend:
